# Generated by Django 3.2.4 on 2021-06-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('fotografia', models.ImageField(upload_to='albums/images/')),
                ('direccion', models.CharField(max_length=100)),
                ('tipo_cliente', models.CharField(choices=[('normal', 'NORMAL'), ('plata', 'PLATA'), ('oro', 'ORO'), ('platino', 'PLATINO')], default='normal', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
