# Generated by Django 3.2.4 on 2021-06-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
    ]
