# Generated by Django 3.2.4 on 2021-06-13 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_proveedor_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaAsociada',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(to='Tienda.Proveedor'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='monto',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('num_pedido', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fecha_genera_pedido', models.DateField(auto_now_add=True)),
                ('fecha_surte_pedido', models.DateField()),
                ('urgente', models.BooleanField(default=False)),
                ('tipo_pedido', models.CharField(choices=[('1', 'Al Centro de Distribución'), ('2', 'A Alguna Sucursal'), ('3', 'A una empresa asociada')], default='1', max_length=1)),
                ('referencia', models.CharField(max_length=10)),
                ('monto_total', models.FloatField(default=0.0)),
                ('almacen_a_surtir_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.almacen')),
                ('cliente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.cliente')),
                ('codigo_socio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.empresaasociada')),
                ('codigo_sucursal_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('monto_unitario', models.FloatField(default=0.0)),
                ('monto_total', models.FloatField(default=0.0)),
                ('articulo_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.articulo')),
                ('pedido_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.pedido')),
            ],
        ),
    ]
