# Generated by Django 3.2.4 on 2021-06-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_auto_20210613_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('monto_unitario', models.FloatField(default=0.0)),
                ('monto_total', models.FloatField(default=0.0)),
                ('articulo_fk', models.ManyToManyField(to='Tienda.Articulo')),
                ('pedido_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.pedido')),
            ],
        ),
    ]
