# Generated by Django 3.2.4 on 2021-06-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_detalle2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detalle2',
        ),
    ]
