# Generated by Django 3.2.4 on 2021-06-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_delete_detalle2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='albums/images/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('1', 'El Centro de Distribución'), ('2', 'Alguna Sucursal'), ('3', 'Una empresa asociada')], default='1', max_length=1),
        ),
    ]
