# Generated by Django 3.2.4 on 2021-06-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_auto_20210616_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='monto_unitario',
        ),
    ]
