# Generated by Django 3.2.4 on 2021-06-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0008_auto_20210619_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_surte_pedido',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='referencia',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
